version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock
    container_name: wiremock-fake-user-api
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock/mappings
    environment:
      WIREMOCK_STUBS_DIR: "/home/wiremock/mappings"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
